package github

const (
	syncerSignature     = "Autogenerated with [peribolos-syncer](https://github.com/maxgio92/peribolos-syncer)."
	ownersDoc           = "https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/#overview"
	peribolosConfigFile = "org.yaml"
)
