package github

const (
	commandName             = "github"
	commandShortDescription = "Synchronize Peribolos config on remote GitHub repositories via Pull Request"
	commandExample          = `
peribolos-syncer sync github --org=acme --team=app-maintainers
--peribolos-config-path=config/org.yaml --peribolos-config-repository=community --peribolos-config-git-ref=main
--owners-repository=app --owners-git-ref=main --owners-path=OWNERS
--github-username=bot --github-token-path=./bot_token
--git-author-name=bot --git-author-email="bot@acme.org"
--gpg-public-key=./bot.pub --gpg-private-key=./bot.asc
`

	syncerSignature     = "Autogenerated with [peribolos-syncer](https://github.com/maxgio92/peribolos-syncer)."
	ownersDoc           = "https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/#overview"
	peribolosConfigFile = "org.yaml"
)
