linters-settings:
  govet:
    check-shadowing: true
  cyclop:
    max-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/falcosecurity/peribolos-syncer) # Groups all imports with the specified Prefix.
  tagliatelle:
    case:
      rules:
        json: snake

linters:
  enable-all: true
  disable:
    - interfacer
    - godox
    - golint
    - scopelint
    - maligned
    - gochecknoglobals
    - gochecknoinits
    - exhaustivestruct
    - exhaustruct
    - ireturn
    - lll
    - nonamedreturns
    - varnamelen
    - depguard
    - wrapcheck

issues:
  exclude-rules:
  - path: /
    linters:
    - typecheck
  - path: _test.go
    linters:
    - revive
    - ineffassign
    - staticcheck
    - errcheck

