project_name: peribolos-owners-syncer

before:
  hooks:
  - go mod tidy
  - go generate ./...
  - go vet ./...

builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ldflags: |
    -X main.buildVersion={{ .Version }}
    -s
    -w

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
    - '^[^S][^L][^-][^\d+]*'

